Fix HTTP status code
Typo, '40 ' instead of '406'.

Found by accident through `checkpatch.pl`:

```
ERROR: space prohibited before that ':' (ctx:WxW)
+               case 400: case 401: case 402: case 403: case 404: case 405: case 40 : case 407: case 408: case 409:
```